---
server:
  port: 8090
---
spring:
  profiles: default,local
  jpa.show-sql : true
  jpa.generate-ddl : true
  jpa: 
   hibernate: 
    ddl-auto: create-drop
  datasource:
   url : jdbc:hsqldb:mem:db_account
   username : sa
   password : 
   driverClassName : org.hsqldb.jdbcDriver
   testWhileIdle : true
   validationQuery : SELECT 1
max:
 recent:
  transactions : 10
kafka:
  bootstrap-servers: localhost:9092
  topic: cashPoC
---
spring:
  profiles: postgresql
  jpa.show-sql : true
  jpa.generate-ddl : true
  datasource:
   url : jdbc:postgresql://localhost:5432/db_account
   username : postgres
   password : admin
   driverClassName : org.postgresql.Driver
   testWhileIdle : true
   validationQuery : SELECT 1
max:
 recent:
  transactions : 10
kafka:
  bootstrap-servers: localhost:9092
  topic: cashPoC
---
spring:
  profiles: mysql
  jpa.show-sql : true
  jpa.generate-ddl : true
  datasource:
   url : jdbc:mysql://localhost:3306/db_account
   username : root
   password : India123
   driverClassName : com.mysql.jdbc.Driver
   testWhileIdle : true
   validationQuery : SELECT 1
max:
 recent:
  transactions : 10
kafka:
  bootstrap-servers: localhost:9092
  topic: cashPoC
---
spring:
  profiles: docker
  jpa.show-sql : true
  jpa.generate-ddl : true
  datasource:
   url : jdbc:postgresql://192.168.99.100:5432/db_account
   username : postgres
   password : postgres
   driverClassName : org.postgresql.Driver
   testWhileIdle : true
   validationQuery : SELECT 1
max:
 recent:
  transactions : 10
kafka:
  bootstrap-servers: localhost:9092
  topic: cashPoC