---
server:
  port: ${PORT:2222}
---
spring:
  profiles: default,local
  application:
    name: cashPoC-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  
  jpa.show-sql : true
  jpa.generate-ddl : true
  jpa: 
   hibernate: 
    ddl-auto: create-drop
  datasource:
   url : jdbc:hsqldb:mem:db_account
   username : sa
   password : 
   driverClassName : org.hsqldb.jdbcDriver
   testWhileIdle : true
   validationQuery : SELECT 1
max:
 recent:
  transactions : 10
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2      
ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: postgresql
  jpa.show-sql : true
  jpa.generate-ddl : true
  datasource:
   url : jdbc:postgresql://localhost:5432/db_account
   username : postgres
   password : admin
   driverClassName : org.postgresql.Driver
   testWhileIdle : true
   validationQuery : SELECT 1
max:
 recent:
  transactions : 10
kafka:
  bootstrap-servers: localhost:9092
  topic: cashPoC
---
spring:
  profiles: mysql
  jpa.show-sql : true
  jpa.generate-ddl : true
  datasource:
   url : jdbc:mysql://localhost:3306/db_account
   username : root
   password : India123
   driverClassName : com.mysql.jdbc.Driver
   testWhileIdle : true
   validationQuery : SELECT 1
max:
 recent:
  transactions : 10
kafka:
  bootstrap-servers: localhost:9092
  topic: cashPoC
---
spring:
  profiles: docker
  jpa.show-sql : true
  jpa.generate-ddl : true
  datasource:
   url : jdbc:postgresql://192.168.99.100:5432/db_account
   username : postgres
   password : postgres
   driverClassName : org.postgresql.Driver
   testWhileIdle : true
   validationQuery : SELECT 1
max:
 recent:
  transactions : 10
kafka:
  bootstrap-servers: localhost:9092
  topic: cashPoC
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true