info:
  component: Edge Server  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
zuul:
  routes:
    account: 
      path: /a/**
      serviceId: cashPoC-service
ribbon:
  eureka:
    enabled: true
server:
  port: 8765
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG    
hystrix:
 command:
  default:
   execution:
    timeout:
     enabled: false
---
spring:
  profiles: default,local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
---      
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
    registerWithEureka: false
---