spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/db_account
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
